---
version: '3.8'

services:
  manga-app:
    image: valiantlynx/svelte-manga:latest
    ports:
      - "8080:3000"
    restart: always
    networks:
      - webnet

  blog-app:
    image: valiantlynx/svelte-altlokalt:latest
    ports:
      - "8081:3000"
    restart: always
    networks:
      - webnet

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - manga-app
      - blog-app
    restart: always
    networks:
      - webnet

  certbot:
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./certbot-data:/data/letsencrypt
    depends_on:
      - nginx
    restart: always
    command: certonly --webroot --webroot-path=/data/letsencrypt --email valiantlynxz@gmail.com --agree-tos --no-eff-email --staging -d animevariant.com -d nebulamanga.com -d astromanga.com -d www.animevariant.com -d www.nebulamanga.com -d www.astromanga.com

networks:
  webnet:
