---
version: '3.8'

services:
  svelte-altlokalt:
    image: valiantlynx/svelte-altlokalt:latest
    container_name: svelte-altlokalt
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/logs:/var/log/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - svelte-altlokalt
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/logs:/var/log/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: >
      certonly --webroot -w /var/www/certbot --force-renewal --email valiantlynxz@gmail.com
      -d altlokal.no -d www.altlokal.no
      -d altlokalt.com -d www.altlokalt.com
      -d digilokal.no -d www.digilokal.no
      -d digilokale.com -d www.digilokale.com
      -d digilokale.no -d www.digilokale.no
      -d dinlokal.no -d www.dinlokal.no
      -d minlokal.no -d www.minlokal.no
      -d blioppdage.com -d www.blioppdage.com
      -d blioppdage.no -d www.blioppdage.no
      -d blioppdaget.com -d www.blioppdaget.com
      -d bovimobilitet.no -d www.bovimobilitet.no
      -d bovimobility.com -d www.bovimobility.com
      -d bovimobility.no -d www.bovimobility.no
      -d digicv.no -d www.digicv.no
      -d digisoknad.no -d www.digisoknad.no
      -d godtilbud.no -d www.godtilbud.no
      -d kunstivestfold.no -d www.kunstivestfold.no
      -d minlokale.com -d www.minlokale.com
      -d minlokale.no -d www.minlokale.no
      -d smartinnovativeproduct.com -d www.smartinnovativeproduct.com
      -d smartinnovativeproduct.no -d www.smartinnovativeproduct.no
      -d smartinnovativeproducts.com -d www.smartinnovativeproducts.com
      -d smartinnovativeproducts.no -d www.smartinnovativeproducts.no
      -d vestfoldkunst.com -d www.vestfoldkunst.com
      --agree-tos --non-interactive



