---
- name: Copy Docker Compose file to the EC2 instance
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/docker-compose.yml"
    src: "docker/docker-compose.yml"
    mode: "0644"
    force: true


- name: copy Nginx configuration files to the EC2 instance
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/nginx/"
    src: "nginx"
    mode: "0644"
    directory_mode: 0755
    force: true
  ignore_errors: true

- name: Pull the latest images with Docker Compose
  become: true
  command: docker-compose pull

- name: Deploy services using Docker Compose
  become: true
  command: docker-compose up -d

- name: Schedule automated certificate renewal
  ansible.builtin.cron:
    name: "Renew Let's Encrypt certificates"
    day: "1"
    month: "*/2"
    hour: "5"
    minute: "0"
    job: "/usr/bin/docker compose -f {{ ansible_user_dir }}/docker-compose.yml up certbot"
    user: root