version: "3.8"
services:
  svelte-altlokalt:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - valiantlynx_network
    restart: always

networks:
  valiantlynx_network:
    name: valiantlynx_network
    driver: bridge # Use the default bridge network
