- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Setup Nginx configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default
  notify: restart nginx
