---
- hosts: ec2_instances
  become: true
  vars_files:
    - group_vars/all.yml

  roles:
    - common
    - docker
    - docker_deploy
    - nginx  # This initial run should only configure Nginx for HTTP.

  tasks:
    # This task assumes the certbot role has already been adjusted to obtain SSL certificates
    # but does not automatically update Nginx configurations for HTTPS.
    - name: Request SSL certificates (handled inside certbot role)
      include_role:
        name: certbot

    - name: Update Nginx configuration for HTTPS
      become: true
      template:
        src: roles/nginx/templates/nginx_https.conf.j2
        dest: /etc/nginx/sites-available/default
      notify: restart nginx


  handlers:
    - name: restart nginx
      become: true
      service:
        name: nginx
        state: restarted
