---
- hosts: ec2_instances
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker dependencies
      apt:
        name:
          - docker.io
          - python3-pip
        state: present

    - name: Install Docker Compose
      pip:
        name: docker-compose
        state: present
        executable: pip3

    - name: Remove existing Docker container
      command: docker rm -f node-app-container
      ignore_errors: yes

    - name: Remove existing Docker image
      command: docker rmi valiantlynx/svelte-altlokalt:latest
      ignore_errors: yes

    - name: Pull new Docker image
      command: docker pull valiantlynx/svelte-altlokalt:latest

    - name: Run Docker container
      command: docker run -d -p 80:3000 --name node-app-container valiantlynx/svelte-altlokalt:latest