- name: Ensure Certbot Nginx Options File Exists
  become: true
  block:
    - name: Check if options-ssl-nginx.conf exists
      stat:
        path: /etc/letsencrypt/options-ssl-nginx.conf
      register: options_ssl_nginx_conf

    - name: Create minimal options-ssl-nginx.conf if missing
      copy:
        dest: /etc/letsencrypt/options-ssl-nginx.conf
        content: |
          ssl_session_cache shared:le_nginx_SSL:1m;
          ssl_session_timeout 1440m;
          ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
          ssl_prefer_server_ciphers on;
      when: not options_ssl_nginx_conf.stat.exists

- name: Install Certbot and Nginx plugin
  become: true
  apt:
    name: python3-certbot-nginx
    state: present

- name: Request Certificates with Certbot for all domains
  become: true
  shell: |
    certbot --nginx \
    {% for domain in item.domains -%}
    -d {{ domain }} \
    {% endfor %}
    --expand --non-interactive --agree-tos -m valiantlynxz@gmail.com --redirect
  loop: "{{ docker_containers }}"
  when: item.ssl_enabled | default(false)
  args:
    creates: "/etc/letsencrypt/live/{{ item.domains[0] }}/fullchain.pem"

- name: Setup automatic renewal of SSL certificates
  become: true
  cron:
    name: "Renew Let's Encrypt certificates"
    special_time: daily
    job: "certbot renew --nginx"
    user: root
