- name: Install Certbot
  become: true
  apt:
    name: python3-certbot-nginx
    state: present

- name: Install Certbot and request certificates for all domains
  become: true
  shell: |
    certbot --nginx \
    {% for domain in item.domains -%}
    -d {{ domain }} \
    {% endfor -%}
    --expand --non-interactive --agree-tos -m valiantlynxz@gmail.com --redirect
  loop: "{{ docker_containers }}"
  when: item.ssl_enabled | default(false)
  args:
    creates: "/etc/letsencrypt/live/{{ item.domains[0] }}/fullchain.pem"

- name: Setup automatic renewal of SSL certificates
  cron:
    name: "Renew Let's Encrypt certificates"
    special_time: daily
    job: "certbot renew --nginx"
    user: root
