- name: Install Certbot
  apt:
    name: python3-certbot-nginx
    state: present

- name: Generate list of unique domains
  set_fact:
    unique_domains_list: "{{ docker_containers | map(attribute='domains') | flatten | unique }}"

- name: Request Certificates with Certbot for unique domains
  become: true
  shell: certbot --nginx -d {{ unique_domains_list | join(' -d ') }} --expand --non-interactive --agree-tos -m valiantlynxz@gmail.com --redirect
  ignore_errors: yes
  register: certbot_command
  changed_when: "'Congratulations' in certbot_command.stdout"

- name: Reload Nginx if certificates were successfully obtained
  become: true
  service:
    name: nginx
    state: reloaded
  when: certbot_command is changed


- name: Setup automatic renewal of SSL certificates
  cron:
    name: "Renew Let's Encrypt certificates"
    special_time: daily
    job: "certbot renew --nginx"
    user: root
